/**
 * 小米备份文件解密工具 - 常量定义
 * 
 * @author NNNNzs
 */

// Android 备份文件常量
module.exports = {
  BACKUP_FILE_HEADER_MAGIC: "ANDROID BACKUP\n",
  BACKUP_FILE_V1: 1,
  BACKUP_FILE_V2: 2,
  BACKUP_FILE_V3: 3,
  BACKUP_FILE_V4: 4,
  BACKUP_FILE_V5: 5,  // 添加版本5的支持
  ENCRYPTION_ALGORITHM_NAME: "AES-256",
  ENCRYPTION_MECHANISM: "aes-256-cbc",
  PBKDF2_HASH_ALGORITHM: "sha1",
  PBKDF2_KEY_SIZE: 32, // 256 bits
  PBKDF2_DEFAULT_ITERATIONS: 10000,
  MASTER_KEY_SIZE: 256, // bits
  PBKDF2_SALT_SIZE: 512, // bits
  DEFAULT_CHARSET: "utf-8"
}; 